version: '3.9'

services:
  api:
    build:
      context: ./
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3001:3001
